# Generated by Django 4.0.1 on 2022-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_link_user_link_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='email',
        ),
        migrations.AddField(
            model_name='link',
            name='user_id',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
